from __future__ import annotations


EXPECTED_ROOT_EXPORTS = {
    "__version__",
    "BenchmarkDefinition",
    "BenchmarkDefinitionConfig",
    "BenchmarkResult",
    "BenchmarkSpec",
    "DatasetQuerySpec",
    "EngineCapabilities",
    "ExecutionPolicySpec",
    "InferenceGridSpec",
    "InferenceParamsSpec",
    "McpServerSpec",
    "ModelSpec",
    "Orchestrator",
    "ParseSpec",
    "PluginRegistry",
    "PostgresBlobStorageSpec",
    "ProjectSpec",
    "PromptMessage",
    "PromptTurnSpec",
    "PromptVariantSpec",
    "ScoreSpec",
    "SliceSpec",
    "SqliteBlobStorageSpec",
    "StorageConfig",
    "StorageSpec",
    "ToolSpec",
    "build_benchmark_definition_project",
    "generate_config_report",
}
