"""Concrete report exporters for CSV, Markdown, and LaTeX outputs."""

from __future__ import annotations

from pathlib import Path

from themis._optional import import_optional
from themis.contracts.protocols import ReportExporter
from themis.records.report import EvaluationReport
from themis.types.json_types import JSONDict


def _table_columns(table_data: list[JSONDict]) -> list[str]:
    columns: list[str] = []
    for row in table_data:
        for key in row:
            if key not in columns:
                columns.append(key)
    return columns


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _render_markdown_table(table_data: list[JSONDict]) -> str:
    if not table_data:
        return "_No rows_\n"
    columns = _table_columns(table_data)
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    rows = [
        "| "
        + " | ".join(_markdown_cell(row.get(column, "")) for column in columns)
        + " |"
        for row in table_data
    ]
    return "\n".join([header, separator, *rows]) + "\n"


def _latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text.replace("\n", r"\\")


def _render_latex_table(table_data: list[JSONDict]) -> str:
    if not table_data:
        return "\\textit{No rows}\n"
    columns = _table_columns(table_data)
    align = "l" * len(columns)
    header = " & ".join(_latex_escape(column) for column in columns) + r" \\"
    body = [
        " & ".join(_latex_escape(row.get(column, "")) for column in columns) + r" \\"
        for row in table_data
    ]
    return "\n".join(
        [
            f"\\begin{{tabular}}{{{align}}}",
            "\\hline",
            header,
            "\\hline",
            *body,
            "\\hline",
            "\\end{tabular}",
            "",
        ]
    )


class CsvExporter(ReportExporter):
    """
    Exports a report to CSV format.
    If a report contains multiple tables, it may prepend table names or output to multiple files.
    Here we implement a simple single-file export (or suffix-based for multiple).
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report tables as CSV files rooted at `path`."""
        pd = import_optional("pandas", extra="stats")
        p = Path(path)
        base = p.parent
        stem = p.stem
        ext = p.suffix if p.suffix else ".csv"

        if not report.tables:
            p.touch()
            return

        for i, table in enumerate(report.tables):
            # If multiple tables, append ordinal or id
            file_path = (
                base / f"{stem}_{table.id}{ext}" if len(report.tables) > 1 else p
            )

            # Use pandas to save CSV
            df = pd.DataFrame(table.data)
            df.to_csv(file_path, index=False)


class MarkdownExporter(ReportExporter):
    """
    Exports a report to GitHub-flavored Markdown.
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report as one Markdown document."""
        if not report.tables:
            Path(path).touch()
            return

        with open(path, "w") as f:
            f.write("# Evaluation Report\n\n")

            for table in report.tables:
                f.write(f"## {table.title}\n")
                if table.description:
                    f.write(f"{table.description}\n")
                f.write("\n")
                f.write(_render_markdown_table(table.data))
                f.write("\n")

            f.write("## Metadata\n")
            f.write(f"* Themis Version: {report.metadata.themis_version}\n")
            f.write(f"* Spec Hashes: {', '.join(report.metadata.spec_hashes)}\n")
            for k, v in report.metadata.extras.items():
                f.write(f"* {k}: {v}\n")


class LatexExporter(ReportExporter):
    """
    Exports a report to LaTeX format.
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report as one LaTeX document."""
        if not report.tables:
            Path(path).touch()
            return

        with open(path, "w") as f:
            f.write("% Evaluation Report Generated by Themis\n")
            f.write("\\section*{Evaluation Report}\n\n")

            for table in report.tables:
                f.write(f"\\subsection*{{{table.title}}}\n")
                if table.description:
                    f.write(f"{table.description}\n")
                f.write("\n")
                f.write(_render_latex_table(table.data))
                f.write("\n\n")
