"""Concrete report exporters for CSV, Markdown, and LaTeX outputs."""

from pathlib import Path

from themis._optional import import_optional
from themis.contracts.protocols import ReportExporter
from themis.records.report import EvaluationReport


class CsvExporter(ReportExporter):
    """
    Exports a report to CSV format.
    If a report contains multiple tables, it may prepend table names or output to multiple files.
    Here we implement a simple single-file export (or suffix-based for multiple).
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report tables as CSV files rooted at `path`."""
        pd = import_optional("pandas", extra="stats")
        p = Path(path)
        base = p.parent
        stem = p.stem
        ext = p.suffix if p.suffix else ".csv"

        if not report.tables:
            p.touch()
            return

        for i, table in enumerate(report.tables):
            # If multiple tables, append ordinal or id
            file_path = (
                base / f"{stem}_{table.id}{ext}" if len(report.tables) > 1 else p
            )

            # Use pandas to save CSV
            df = pd.DataFrame(table.data)
            df.to_csv(file_path, index=False)


class MarkdownExporter(ReportExporter):
    """
    Exports a report to GitHub-flavored Markdown.
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report as one Markdown document."""
        pd = import_optional("pandas", extra="stats")
        if not report.tables:
            Path(path).touch()
            return

        with open(path, "w") as f:
            f.write("# Evaluation Report\n\n")

            for table in report.tables:
                f.write(f"## {table.title}\n")
                if table.description:
                    f.write(f"{table.description}\n")
                f.write("\n")
                df = pd.DataFrame(table.data)
                f.write(df.to_markdown(index=False))
                f.write("\n\n")

            f.write("## Metadata\n")
            f.write(f"* Themis Version: {report.metadata.themis_version}\n")
            f.write(f"* Spec Hashes: {', '.join(report.metadata.spec_hashes)}\n")
            for k, v in report.metadata.extras.items():
                f.write(f"* {k}: {v}\n")


class LatexExporter(ReportExporter):
    """
    Exports a report to LaTeX format.
    """

    def export(self, report: EvaluationReport, path: str) -> None:
        """Write the report as one LaTeX document."""
        pd = import_optional("pandas", extra="stats")
        if not report.tables:
            Path(path).touch()
            return

        with open(path, "w") as f:
            f.write("% Evaluation Report Generated by Themis\n")
            f.write("\\section*{Evaluation Report}\n\n")

            for table in report.tables:
                f.write(f"\\subsection*{{{table.title}}}\n")
                if table.description:
                    f.write(f"{table.description}\n")
                f.write("\n")
                df = pd.DataFrame(table.data)
                f.write(df.to_latex(index=False))
                f.write("\n\n")
