"""Public package surface for Themis."""

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import tomllib

from themis.core import (
    CodeExecutionLimits,
    CodeExecutionRequest,
    CodeExecutionResult,
    CodeExecutionStatus,
    DatasetSourceSpec,
    DockerExecutionBackend,
    EvaluationGraph,
    EvaluationStep,
    Experiment,
    ExecutionBackend,
    ExecutionCheckpoint,
    ExecutionResourcePlan,
    ExecutionRequest,
    FailureSlice,
    FailureSliceSummary,
    FilesystemExecutionBackend,
    GraphRuntime,
    GraphRunResult,
    InMemoryRunStore,
    InMemoryExecutionBackend,
    LocalSubprocessExecutionBackend,
    PairwiseComparisonReport,
    PairwiseMetricClaim,
    PromptSpec,
    ProviderCallCompletedEvent,
    ProviderCallFailedEvent,
    ProviderCallStartedEvent,
    ProviderTelemetry,
    QueueExecutionBackend,
    Reporter,
    ReporterProtocol,
    RegressionFinding,
    RegressionPolicy,
    RegressionSummary,
    ReliabilitySummary,
    RuntimeConfig,
    RuntimePreset,
    SessionConfig,
    SessionPreset,
    StageTelemetry,
    SuiteCoverageSummary,
    RunEstimate,
    RunLineage,
    RunQuery,
    RunRecord,
    RunResult,
    RunSnapshot,
    RunStatus,
    RunStore,
    ProjectionCursor,
    RerunPlan,
    RerunSelector,
    SqliteRunStore,
    StatsEngine,
    TrendPoint,
    TrendView,
    EvaluationPreset,
    ExperimentPreset,
    apply_preset,
    available_reporters,
    create_reporter,
    get_case_audit,
    get_evaluation_execution,
    get_execution_state,
    get_run_record,
    get_run_snapshot,
    get_telemetry_summary,
    get_preset,
    list_presets,
    sqlite_store,
    StepInput,
    StepOutput,
    register_reporter,
)


def _resolve_version() -> str:
    """Resolve the installed package version with a source-tree fallback."""

    try:
        return version("themis-eval")
    except PackageNotFoundError:
        pyproject_path = Path(__file__).resolve().parents[1] / "pyproject.toml"
        if pyproject_path.is_file():
            payload = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
            return str(payload["project"]["version"])
        return "0+unknown"


__version__ = _resolve_version()

__all__ = [
    "Experiment",
    "CodeExecutionLimits",
    "CodeExecutionRequest",
    "CodeExecutionResult",
    "CodeExecutionStatus",
    "EvaluationGraph",
    "EvaluationStep",
    "ExecutionBackend",
    "ExecutionCheckpoint",
    "ExecutionResourcePlan",
    "ExecutionRequest",
    "DatasetSourceSpec",
    "DockerExecutionBackend",
    "FailureSlice",
    "FailureSliceSummary",
    "FilesystemExecutionBackend",
    "GraphRuntime",
    "GraphRunResult",
    "InMemoryRunStore",
    "InMemoryExecutionBackend",
    "LocalSubprocessExecutionBackend",
    "PairwiseComparisonReport",
    "PairwiseMetricClaim",
    "PromptSpec",
    "ProviderCallCompletedEvent",
    "ProviderCallFailedEvent",
    "ProviderCallStartedEvent",
    "ProviderTelemetry",
    "QueueExecutionBackend",
    "Reporter",
    "ReporterProtocol",
    "RuntimeConfig",
    "RuntimePreset",
    "SessionConfig",
    "SessionPreset",
    "RunEstimate",
    "RunLineage",
    "RunQuery",
    "RunRecord",
    "RunResult",
    "RunSnapshot",
    "RunStatus",
    "RunStore",
    "ProjectionCursor",
    "RerunPlan",
    "RerunSelector",
    "__version__",
    "RegressionFinding",
    "RegressionPolicy",
    "RegressionSummary",
    "ReliabilitySummary",
    "SqliteRunStore",
    "StageTelemetry",
    "SuiteCoverageSummary",
    "StatsEngine",
    "TrendPoint",
    "TrendView",
    "EvaluationPreset",
    "ExperimentPreset",
    "apply_preset",
    "available_reporters",
    "create_reporter",
    "get_case_audit",
    "get_evaluation_execution",
    "get_execution_state",
    "get_run_record",
    "get_run_snapshot",
    "get_telemetry_summary",
    "get_preset",
    "list_presets",
    "sqlite_store",
    "StepInput",
    "StepOutput",
    "register_reporter",
]
