"""Public contracts for custom Themis components."""

from themis.core.contexts import (
    EvalScoreContext,
    GenerationContext,
    ParseContext,
    ReduceContext,
    ScoreContext,
    SelectContext,
)
from themis.core.models import (
    Case,
    Candidate,
    ConversationTrace,
    GenerationTurn,
    Message,
    MetricDirection,
    MetricInterpretation,
    MetricResult,
    ParsedOutput,
    ReducedCandidate,
    ScoreError,
    StreamEvent,
    SeedCapability,
    TraceStep,
    WorkflowTrace,
)
from themis.core.protocols import (
    CandidateReducer,
    CandidateSelector,
    EvaluationWorkflow,
    Generator,
    JudgeModel,
    MetricSubjectKind,
    Parser,
    PureMetric,
    WorkflowMetric,
    WorkflowRunner,
)
from themis.core.prompts import PromptSpec
from themis.core.subjects import (
    CandidateSetSubject,
    CandidateSubject,
    ConversationSubject,
    TraceSubject,
)
from themis.core.workflows import (
    AggregationResult,
    EvaluationExecution,
    JudgeCall,
    JudgeResponse,
    ParsedJudgment,
    RenderedJudgePrompt,
    WorkflowFailure,
    WorkflowStatus,
    WorkflowSubjectKind,
)

__all__ = [
    "AggregationResult",
    "Case",
    "Candidate",
    "CandidateSetSubject",
    "CandidateSubject",
    "CandidateReducer",
    "CandidateSelector",
    "ConversationTrace",
    "ConversationSubject",
    "EvalScoreContext",
    "EvaluationExecution",
    "EvaluationWorkflow",
    "GenerationContext",
    "GenerationTurn",
    "Generator",
    "JudgeCall",
    "JudgeModel",
    "JudgeResponse",
    "Message",
    "MetricDirection",
    "MetricInterpretation",
    "MetricResult",
    "MetricSubjectKind",
    "ParsedJudgment",
    "ParsedOutput",
    "ParseContext",
    "Parser",
    "PromptSpec",
    "PureMetric",
    "RenderedJudgePrompt",
    "ReducedCandidate",
    "ReduceContext",
    "ScoreContext",
    "ScoreError",
    "SelectContext",
    "SeedCapability",
    "StreamEvent",
    "TraceStep",
    "TraceSubject",
    "WorkflowFailure",
    "WorkflowMetric",
    "WorkflowRunner",
    "WorkflowStatus",
    "WorkflowSubjectKind",
    "WorkflowTrace",
]
