"""Core namespace for Themis v4 Phase 3."""

from themis.core.base import FrozenModel, HashableModel, JSONValue
from themis.core.bundles import (
    export_evaluation_bundle,
    export_generation_bundle,
    import_evaluation_bundle,
    import_generation_bundle,
)
from themis.core.builtins import resolve_judge_model_component
from themis.core.config import EvaluationConfig, GenerationConfig, RuntimeConfig, StorageConfig
from themis.core.contexts import (
    EvalScoreContext,
    GenerateContext,
    ParseContext,
    ReduceContext,
    ScoreContext,
)
from themis.core.events import (
    EvaluationCompletedEvent,
    EvaluationFailedEvent,
    GenerationCompletedEvent,
    GenerationFailedEvent,
    ParseCompletedEvent,
    ParseFailedEvent,
    ReductionCompletedEvent,
    ReductionFailedEvent,
    RunCompletedEvent,
    RunEvent,
    RunFailedEvent,
    RunStartedEvent,
    ScoreCompletedEvent,
    ScoreFailedEvent,
    StepCompletedEvent,
    StepFailedEvent,
    StepStartedEvent,
    event_from_dict,
)
from themis.core.experiment import Experiment
from themis.core.inspection import get_evaluation_execution, get_execution_state
from themis.core.quickcheck import quickcheck
from themis.core.read_models import BenchmarkResult, TimelineView, TraceView
from themis.core.reporter import Reporter, snapshot_report
from themis.core.models import (
    Case,
    ConversationTrace,
    Dataset,
    GenerationResult,
    Message,
    ParsedOutput,
    ReducedCandidate,
    Score,
    ScoreError,
    TraceStep,
    WorkflowTrace,
)
from themis.core.protocols import (
    AfterGenerate,
    AfterJudge,
    AfterParse,
    AfterReduce,
    AfterScore,
    BeforeGenerate,
    BeforeJudge,
    BeforeParse,
    BeforeReduce,
    BeforeScore,
    CandidateReducer,
    EvaluationWorkflow,
    Generator,
    JudgeModel,
    LLMMetric,
    LifecycleSubscriber,
    OnEvent,
    Parser,
    PureMetric,
    SelectionMetric,
    TraceMetric,
    TracingProvider,
    WorkflowRunner,
)
from themis.core.orchestrator import Orchestrator
from themis.core.planner import Planner
from themis.core.results import (
    CaseResult,
    EvaluationBundle,
    EvaluationBundleRecord,
    ExecutionState,
    GenerationBundle,
    GenerationBundleRecord,
    GenerationWorkItem,
    ProgressSnapshot,
    RunResult,
    RunStatus,
)
from themis.core.store import RunStore
from themis.core.snapshot import (
    ComponentRef,
    ComponentRefs,
    DatasetRef,
    RunIdentity,
    RunProvenance,
    RunSnapshot,
    StoredRun,
)
from themis.core.subjects import (
    CandidateSetSubject,
    ConversationSubject,
    TraceSubject,
    candidate_set_subject_for_llm_metric,
    candidate_set_subject_for_selection_metric,
    validate_candidate_set_for_llm_metric,
    validate_candidate_set_for_selection_metric,
)
from themis.core.stores import InMemoryRunStore, SqliteRunStore, sqlite_store
from themis.core.tracing import NoOpTracingProvider
from themis.core.workflow_runner import WorkflowBuildError
from themis.core.workflow_runner import DefaultWorkflowRunner
from themis.core.workflows import (
    AggregationResult,
    EvaluationExecution,
    JudgeCall,
    JudgeResponse,
    ParsedJudgment,
    RenderedJudgePrompt,
    build_prompt_template_context,
)

__all__ = [
    "Case",
    "DefaultWorkflowRunner",
    "BeforeGenerate",
    "AfterGenerate",
    "BeforeReduce",
    "AfterReduce",
    "BeforeParse",
    "AfterParse",
    "BeforeScore",
    "AfterScore",
    "BeforeJudge",
    "AfterJudge",
    "BenchmarkResult",
    "CandidateReducer",
    "CandidateSetSubject",
    "ComponentRef",
    "ComponentRefs",
    "ConversationTrace",
    "ConversationSubject",
    "Dataset",
    "DatasetRef",
    "EvalScoreContext",
    "EvaluationExecution",
    "EvaluationCompletedEvent",
    "EvaluationFailedEvent",
    "EvaluationConfig",
    "EvaluationWorkflow",
    "Experiment",
    "FrozenModel",
    "Generator",
    "GenerateContext",
    "GenerationCompletedEvent",
    "GenerationFailedEvent",
    "GenerationConfig",
    "GenerationResult",
    "GenerationWorkItem",
    "HashableModel",
    "JudgeModel",
    "JudgeCall",
    "JudgeResponse",
    "JSONValue",
    "LLMMetric",
    "LifecycleSubscriber",
    "Message",
    "NoOpTracingProvider",
    "Orchestrator",
    "AggregationResult",
    "OnEvent",
    "ParseCompletedEvent",
    "ParseFailedEvent",
    "ParseContext",
    "ParsedOutput",
    "ParsedJudgment",
    "Parser",
    "PureMetric",
    "Planner",
    "RenderedJudgePrompt",
    "ReduceContext",
    "ReducedCandidate",
    "ReductionCompletedEvent",
    "ReductionFailedEvent",
    "RunCompletedEvent",
    "RunEvent",
    "RunFailedEvent",
    "RunResult",
    "RunIdentity",
    "RunProvenance",
    "RunSnapshot",
    "RunStartedEvent",
    "RunStatus",
    "RunStore",
    "RuntimeConfig",
    "snapshot_report",
    "CaseResult",
    "EvaluationBundle",
    "EvaluationBundleRecord",
    "ExecutionState",
    "export_evaluation_bundle",
    "export_generation_bundle",
    "GenerationBundle",
    "GenerationBundleRecord",
    "get_evaluation_execution",
    "get_execution_state",
    "ProgressSnapshot",
    "quickcheck",
    "Reporter",
    "Score",
    "ScoreCompletedEvent",
    "ScoreContext",
    "ScoreError",
    "ScoreFailedEvent",
    "SelectionMetric",
    "SqliteRunStore",
    "StepCompletedEvent",
    "StepFailedEvent",
    "StepStartedEvent",
    "StoredRun",
    "StorageConfig",
    "TraceMetric",
    "TraceStep",
    "TraceSubject",
    "TimelineView",
    "TracingProvider",
    "TraceView",
    "WorkflowBuildError",
    "WorkflowRunner",
    "WorkflowTrace",
    "build_prompt_template_context",
    "candidate_set_subject_for_llm_metric",
    "candidate_set_subject_for_selection_metric",
    "event_from_dict",
    "InMemoryRunStore",
    "import_evaluation_bundle",
    "import_generation_bundle",
    "resolve_judge_model_component",
    "sqlite_store",
    "validate_candidate_set_for_llm_metric",
    "validate_candidate_set_for_selection_metric",
]
